name: Guestbook Workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *'
  issues:
    types: [opened, closed, reopened, deleted, edited]
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update_guestbook:
    name: Update this repo's README with guestbook's latest activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update guestbook with the latest guest post entries
        uses: nfhipona/guestbook-workflow@main
        with:
          target_branch: 'guestbook'
          section_identifier: 'guestbook-section'
          include_body_formatting: true # this already defaults to true -- just for demo
          close_outdated_issues: true
          entry_labels: 'guestbook'
          comment_template: '| <sub> **[$username]($profile)** • $date <kbd>$title</kbd> </sub> <br> $content |\n|:---|'
          comment_empty_title_template: '| <sub> **[$username]($profile)** • $date <kbd>$title</kbd> </sub> <br> $content |\n|:---|'
